#!/usr/bin/with-contenv bash

if [[ ! -d /mnt/config/www/grav ]]; then
  if [[ ! -f /usr/lib/php/composer.phar ]]; then
    if [[ ! -f /usr/src/composer.phar ]]; then
      cd /usr/src
      wget https://raw.githubusercontent.com/composer/getcomposer.org/master/web/installer -O - -q | php -- --quiet
    fi
    mv /usr/src/composer.phar /usr/lib/php/composer.phar
    chown guardian:users /root && chown -R guardian:users /root/.composer
  fi
  cd /mnt/config/www
  HOME=/mnt/config/home s6-setuidgid guardian /usr/lib/php/composer.phar create-project getgrav/grav /mnt/config/www/grav
  cd grav
  HOME=/mnt/config/home s6-setuidgid guardian ./bin/gpm -y install admin
  HOME=/mnt/config/home s6-setuidgid guardian ./bin/gpm -y install cookieconsent
  HOME=/mnt/config/home s6-setuidgid guardian ./bin/gpm -y install external_links
  HOME=/mnt/config/home s6-setuidgid guardian ./bin/gpm -y install pagination
  HOME=/mnt/config/home s6-setuidgid guardian ./bin/gpm -y install simplesearch
  HOME=/mnt/config/home s6-setuidgid guardian ./bin/gpm -y install sitemap
  echo 'Sitemap: /sitemap.xml' >>/mnt/config/www/grav/robots.txt
  chown -R guardian:users /mnt/config/www/grav
elif [[ -f /mnt/config/etc/update-grav || -f /mnt/config/etc/update-grav.once ]]; then
  if [[ -f /mnt/config/etc/update-grav.once ]]; then rm -f /mnt/config/etc/update-grav.once; fi
  cd /mnt/config/www/grav
  HOME=/mnt/config/home s6-setuidgid guardian ./bin/grav backup && \
  HOME=/mnt/config/home s6-setuidgid guardian ./bin/grav composer && \
  HOME=/mnt/config/home s6-setuidgid guardian ./bin/gpm -y self-upgrade && \
  HOME=/mnt/config/home s6-setuidgid guardian ./bin/gpm -y update && \
  HOME=/mnt/config/home s6-setuidgid guardian ./bin/grav backup
  find /mnt/config/www/grav/backup/ -maxdepth 1 -type f -name *.zip | sort | tail -n +7 | xargs -0 rm -f --
fi